#!/bin/bash

if [ -z "$1" ]; then
	echo "Provide an endpoint"
fi

if [ -z "${MARVEL_PUBLIC_KEY}" ]; then
	echo "Set MARVEL_PUBLIC_KEY environment variable"
	exit 1
fi

if [ -z "${MARVEL_PRIVATE_KEY}" ]; then
	echo "Set MARVEL_PUBLIC_KEY environment variable"
        exit 1
fi

ENDPOINT=$1
API_URL="https://gateway.marvel.com:443/v1/public"
NONCE=`date "+%s"`
KEY="${NONCE}${MARVEL_PRIVATE_KEY}${MARVEL_PUBLIC_KEY}"
HASH=`echo -n $KEY | md5`
AUTH_STRING="apikey=${MARVEL_PUBLIC_KEY}&ts=${NONCE}&hash=${HASH}"

REQUEST="${API_URL}/${ENDPOINT}" 
if [[ $ENDPOINT == *"?"* ]]; then
	REQUEST="${REQUEST}&${AUTH_STRING}"
else
	REQUEST="${REQUEST}?${AUTH_STRING}"
fi

OUTPUT_FILE=~/marvel.json

curl --silent $REQUEST | json_pp > $OUTPUT_FILE
subl $OUTPUT_FILE
sleep 1
rm $OUTPUT_FILE

